<?php require('template/header.phtml') ?>

<?php
if (isset($_GET['status'])) {
    if ($_GET['status'] == 'invalid') {
        echo "<h1>Incorrect Username or Password</h1>";
    }
}
?>

<form action='controllers/validatelogin.php' method='post'>
    <p>Username:</p>
    <input type='text' id='usernameinput' name='usernameinput' />
    <p>Password:</p>
    <input type='password' id='passwordinput' name='passwordinput' />
    <input type='submit' value='Login'>
</form>


<?php require('template/footer.phtml') ?>
