<div id="new-message">
    <p class="m-header">New Message</p>
    <p class="m-body">
    <form style="text-align:center;" method="post">
        <input type="text" list="user" onkeyup="check_in_db()" class="message-input" placeholder="username" name="username" id="username" />
        <!-- This datalist will show available user-->
        <datalist id="user"></datalist>

        <br><br>
        <textarea class="message-input" name="message" placeholder="Write your message"></textarea><br><br>
        <input type="submit" value="send" id="send" name="send"/>
        <button onclick="document.getElementById('new-message').style.display='none'">Cancel</button>
    </form>
    </p>
    <p class="m-footer">Click Send to send message</p>
    <!-- end of new message -->
</div>

<?php
    require_once("Controllers/db_connection.php");
    if(isset($_POST['send'])) {
        $q = 'INSERT INTO messages (message_sender, message_reciever, message_content, date_time)
              VALUES ("'.$_SESSION['username'].'", "'.$_POST['username'].'", "'.$_POST['message'].'", NOW());';
        $r = mysqli_query($conn, $q);
        if($r) {
            header("location:messages.php?user=".$_POST['username']);
        }
        else {
            echo $q;
        }
    }
?>

<script>
    document.getElementById("send").disabled = true;
    function check_in_db() {
        var username = document.getElementById("username").value ;
        //send this username to another file check_in_db.php
        $.post("../../Controllers/check_in_db.php",
        {
            user: username
        },
        function(data, status) {
            //alert(data) ;
            if(data == '<option value="no user">') {
                document.getElementById("send").disabled = true;
            } else {
                document.getElementById("send").disabled = false;
            }
            document.getElementById('user').innerHTML = data ;
        }
    );
    }
</script>
