<div id="right-col-container">
    <div id="messages-container">

        <?php
        require_once('Controllers/db_connection.php');
            $no_message = false;
            if(isset($_GET['user'])) {
                $_GET['user'] = $_GET['user'];
            } else {
                //user variable is not in the url bar
                //so select the last user, you have sent message to
                $q='SELECT message_sender, message_reciever FROM messages
                    WHERE message_sender = "'.$_SESSION['username'].'"
                    OR message_reciever = "'.$_SESSION['username'].'"
                    ORDER BY date_time DESC LIMIT 1';
                $r = mysqli_query($conn, $q);
                if($r) {
                    if(mysqli_num_rows($r)>0) {
                        while($row = mysqli_fetch_assoc($r)) {
                            $message_sender = $row['message_sender'];
                            $message_reciever = $row['message_reciever'];

                            if($_SESSION['username'] == $message_sender) {
                                $_GET['user'] = $message_reciever;
                            } else {
                                $_GET['user'] = $message_sender;
                            }
                        }
                    } else {
                        echo 'no messages from you' ;
                        $no_message = true;
                    }
                }
            }

            if($no_message == false){
                $q ='SELECT * FROM messages WHERE message_sender = "'.$_SESSION['username'].'" AND message_reciever = "'.$_GET['user'].'"
                OR message_sender = "'.$_GET['user'].'" AND message_reciever = "'.$_SESSION['username'].'"';
                $r =mysqli_query($conn, $q);
                if($r) {
                    while($row = mysqli_fetch_assoc($r)) {
                        $message_sender = $row['message_sender'];
                        $message_reciever = $row['message_reciever'];
                        $message = $row['message_content'];

                        if($message_sender == $_SESSION['username']) {
                            ?>
                            <div class="grey-message">
                                <a href="#">Me</a>
                                <p><?php echo $message; ?></p>
                            </div>
                            <?php
                        } else {
                            ?>
                            <div class="white-message">
                            <a href="#"><?php echo $message_sender; ?></a>
                            <p><?php echo $message;?></p>
                            </div>
                        <?php
                        }
                    }
                } else {
                    echo $q;
                }
            }
        ?>
        <!-- end of messages container -->
    </div>
    <form method="post" id="message-form">
        <textarea class="textarea" id="message_text" placeholder="Write your message"></textarea>

    </form>
    <!-- end of right column container -->
</div>

<script>
    $("document").ready(function(event){
        $("#right-col-container").on('submit', '#message-form', function(){
           var message_text = $("#message_text").val();
           $.post("Controllers/sending_process.php?user=<?php echo $_GET['user'] ?>",
               {
                   message: message_text,
               },
               function(data, status){
                   $("#message_text").val("");
                   document.getElementById("messages-container").innerHTML += data;
               }
           );
        });

        $("#right-col-container").keypress(function(e){
            if(e.keyCode == 13 && !e.shiftKey) {
                $("#message-form").submit() ;
            }
        });
    });
</script>